
# These directives are choices made by AlternC.
# You can override them by putting different values in 50-yourfile.conf in /etc/nginx/conf.d/

server_tokens off;
# if you apt install libnginx-mod-http-headers-more-filterL you can add that:
# more_clear_headers Server;

# This is big but some client may need this ...
# note: if you use PHP for upload, you need to set post_max_size & upload_max_size too!
client_max_body_size 2000m;

proxy_read_timeout 600s;
proxy_connect_timeout 600s;

proxy_busy_buffers_size 512k;
proxy_buffers 4 512k;
proxy_buffer_size 256k;

server_names_hash_bucket_size 128;

# on debian 10 tls1.3 is already supported (appears in 1.13)
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
# to setup your own dhparam, use
# openssl dhparam -out /etc/ssl/private/dhparam.pem.new 2048
# then uncomment the following : 
#	ssl_dhparam /etc/ssl/private/dhparam.pem;

# Letsencrypt is not using stapling anymore in 2026. we remove this.
#	ssl_stapling on;
#	ssl_stapling_verify on;
# replace this with your DNS resolver to use stapling:
#	resolver 91.194.60.250 91.194.60.251;
ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;


# we add the $request_time (used by people doing nginx_stats) and the host at the end of the line.
log_format withhostandtiming '$remote_addr - $remote_user [$time_local] '
	                    '"$request" $status $body_bytes_sent '
                            '"$http_referer" "$http_user_agent" $request_time $host';

access_log /var/log/nginx/access.log withhostandtiming;

