#!/bin/bash

# ----------------------------------------------------------------------
# AlternC - Web Hosting System
# Copyright (C) 2000-2012 by the AlternC Development Team.
# https://alternc.org/
# ----------------------------------------------------------------------
# LICENSE
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License (GPL)
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# To read the license please visit http://www.gnu.org/copyleft/gpl.html
# ----------------------------------------------------------------------
# Purpose of file: Install nginx conf files.
# ----------------------------------------------------------------------

if [ "$1" = "upgrade" ]
then
    echo "Nginx Configuration:"
    cp /etc/alternc/templates/nginx/nginx.conf /etc/nginx/

#    echo "Reloading Nginx templates:"
#    /usr/lib/alternc/update_nginx-ssl.sh

    echo "----------------------------------------------------------------------"
    echo "PLEASE NOTE THAT YOU NEED TO CREATE AN ACME ACCOUNT USING ACME.SH:"
    echo "acme.sh --register-account  --server <zerossl|letsencrypt> \\"
    echo "    [ --eab-kid <your-provider-kid> --eab-hmac-key <your-provider-hmac> ] "
    echo "acme.sh --set-default-ca  --server <zerossl|letsencrypt>"
    echo "----------------------------------------------------------------------"
    

if [ "$1" = "before-reload" ]
then
    invoke-rc.d nginx stop
    invoke-rc.d nginx start
fi

